name: Push

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-name.outputs.current_branch }}

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Specify Version
        id: android-version
        run: |
          echo "VERSION_NAME=3.1.2" >> $GITHUB_OUTPUT

          echo "VERSION_CODE=26" >> $GITHUB_OUTPUT

      - name: Run Release Drafter
        id: run-release-drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.android-version.outputs.VERSION_NAME }}
          name: 'Test Version ${{ steps.android-version.outputs.VERSION_NAME }}'
          tag: 'v${{ steps.android-version.outputs.VERSION_NAME }}'

      - name: Store Release Assets
        id: store-assets
        run: |
          echo "${{ steps.android-version.outputs.VERSION_NAME }}" > release/versionName.txt
          echo "${{ steps.android-version.outputs.VERSION_CODE }}" > release/versionCode.txt

      - name: Upload Release Assets
        id: upload-release-assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.run-release-drafter.outputs.upload_url }}
          asset_path: ./release/versionName.txt
          asset_name: versionName.txt
      - uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.run-release-drafter.outputs.upload_url }}
          asset_path: ./release/versionCode.txt
          asset_name: versionCode.txt
          
