name: Push

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch-name.outputs.current_branch }}

    steps:
      - name: Download repository
        uses: actions/checkout@v3

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Specify Version
        id: android-version
        run: |
          echo "VERSION_NAME=3.1.2" >> $GITHUB_OUTPUT

          echo "VERSION_CODE=26" >> $GITHUB_OUTPUT

      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        with:
          version: ${{ steps.android-version.outputs.VERSION_NAME }}
          name: 'Test Version ${{ steps.android-version.outputs.VERSION_NAME }}'
          tag: 'v${{ steps.android-version.outputs.VERSION_NAME }}'
